Виконання лабораторної роботи 3
volvinbur1/Java-Labs pull request #1
Opened 2020-03-22 18:08 UTC by volvinbur1

Для виконання був обраний перший варіант: "Турнікет контролює вхід лижників на підйомник по ski-pass."

2020-03-29 10:52 UTC, SDiakov requested changes

2020-03-29 10:52 UTC, SDiakov commented on Ski-pass/src/com/company/CardRegister.java
> +            RegisteredCard.put(identifier, object);
Навіщо викликати put? get поверне посилання на об'єкт і зміни в цьому об'єкті будуть відображені у колекції. Можна також використати replace

2020-03-29 10:52 UTC, SDiakov commented on Ski-pass/src/com/company/PassCard.java
> +    public int TripsNumberLeft; // for kind BY_TRIPS
Надлишкові дані у картки недопустимі. Деяким типам карток потрібна лише кількість поїздок, а деяким термін дії. Побудуйте відповідну ієрархію класів, винісши у базовий клас лише спільні речі.

2020-03-29 10:52 UTC, SDiakov commented on Ski-pass/src/com/company/CardValidator.java
> +        if (passCard.Kind == PassCard.CardKind.EVENING && hourNow >= 14 && hourNow < 19) {
Додавання нового типу картки з новим типом перевірки постійно призводитиме до необхідності змінювати цей клас. Це суперечить принципам SOLID - клас повинен бути відкритим до розширення але закритим для змін.
Якщо CardValidator - це реалізація турнікету, то краще перенести безпосередню логіку перевірки карток у саму модель картки, оголосивши метод для валідації у базовому класі та додавши унікальні перевірки у кожному класі насліднику. Тут працювати як з карткою базового типа скориставшись поліморфізмом.

2020-03-29 11:07 UTC, volvinbur1 commented on Ski-pass/src/com/company/CardRegister.java
> +            RegisteredCard.put(identifier, object);
Окей. я зрозумів. Я зробив так, тому що думав, що поверне просто значення

2020-03-29 12:51 UTC, volvinbur1 commented on Ski-pass/src/com/company/PassCard.java
> +    public int TripsNumberLeft; // for kind BY_TRIPS
Створив базовий клас для карток із загальними даними і два дочірніх для карток із кількістю поїздок та карток валідованих за пройденими днями.

2020-03-29 12:59 UTC, volvinbur1 commented on Ski-pass/src/com/company/CardValidator.java
> +        if (passCard.Kind == PassCard.CardKind.EVENING && hourNow >= 14 && hourNow < 19) {
Так, погоджуюсь, це раціональний підхід. Додав метод для перевірки `Validate` у базовий клас і перевантажив його в дочірніх, аби виконували перевірку за специфічних налаштувань. 

Впринципі, клас `ValidityCard` також можна було б розбити на дочірні, тому що там існує валідація карти за її типом, відповідним до часу доби. Але невпевнений, чи не було б це занадто.

2020-03-29 13:24 UTC, volvinbur1 commented
Впринципі, клас `ValidityCard` також можна було б розбити на дочірні, тому що там існує валідація карти за її типом, відповідним до часу доби. Але невпевнений, чи не було б це занадто?

2020-03-29 15:19 UTC, SDiakov commented on Ski-pass/src/com/company/CardRegister.java
> +            RegisteredCard.put(identifier, object);
> Впринципі, клас `ValidityCard` також можна було б розбити на дочірні, тому що там існує валідація карти за її типом, відповідним до часу доби. Але невпевнений, чи не було б це занадто?

Я тому і запитав про CardValidator. Якщо це реалізація турнікету - то ні, робити окремиф клас турнікету для кожної картки недоцільно.
Якщо ж це просто абстракція, яка містить логіку перевірки валідності картки - то так, можна зберігати цю логіку не у самій картці, а у об'єкті відповідного типу валідатора. А картка вже агрегуватиме валідатор.

2020-03-29 15:33 UTC, SDiakov commented
> Впринципі, клас `ValidityCard` також можна було б розбити на дочірні, тому що там існує валідація карти за її типом, відповідним до часу доби. Але невпевнений, чи не було б це занадто?

Тому я і спитав про те, що являє собою CardValidator.
Якщо цей клас - реалізація турнікету - то не потрібно його розбивати на дочірні, робити окремий турнікет для окремого типу картки недоцільно.
Якщо ж цей клас - просто абстракція, яка містить логіку валідації картки - то можна створити паралельну ієрархію валідаторів, а картка агрегуватиме валідатор. Тоді турнікет треба реалізувати окремо, таким чином, щоб він приймав базову картку.
В будь-якому випадку CardValidator не потрібно видаляти.

2020-03-29 15:34 UTC, SDiakov commented
Зробіть реалізацію турнікету і зарезолвіть конфлікти.

2020-03-29 16:50 UTC, volvinbur1 commented
Так `CardValidator` це реалізація турнікету. Я його повернув і переробив, аби працював.

У попередньому коміті я зробив реалізацію методу `Validate` у класах, які описують кожну картку. І викликав просто цей метод до карти, яку перевірялось.  
Зараз я переніс цей функціонал у клас опису турнікету.

2020-04-05 12:23 UTC, SDiakov commented
"Така ж реалізація також може мати місце? В системі є набір із ідентифікатора карти і об'єкту, який її описує. І типу зчитавши ідетифікатор карти, можна взяти її об'єкт із словника і застосувати метод для валідації, що реалізований в цьому об'єкті."

Я дотримуюсь думки, що такий підхід має сенс. Почитайте про GRASP-патерн "Інформаційний експерт".
Тому попередній коміт мені подобається більше ніж останній у якому є турнікет з instanceof. Але винесення логіки перевірки валідності картки у саму картку не означає видалення класу турнікету. Він також повинен бути і виконувати свою роботу. Припустимо у турнікети буде метод ValidateCard, який прийматиме картку базового типу, здійснюватиме її перевірку, вестиме історію результатів проходу, за потреби - викликатиме метод Warn (читайте умову завдання). Схоже на те, що ви робите у мейні, тільки не вивід на консоль, а запис у відповідні структури даних.

2020-04-05 12:24 UTC, SDiakov requested changes
Поверніться до попереднього коміту і поверніть турнікет.

2020-04-05 15:42 UTC, volvinbur1 commented
Все, я запушив кінцевий результат.

2020-04-07 07:45 UTC, merged